version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/power-of-attorney

    steps:
      - checkout

      - restore_cache:
          keys:
            - power-of-attorney-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: power-of-attorney-{{ checksum "pom.xml" }}

      - run: mvn clean test